// <auto-generated />
using System;
using Aixaminator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aixaminator.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002104403_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Aixaminator.Data.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Aixaminator.Data.DocumentPart", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseColour")
                        .HasColumnType("INTEGER");

                    b.HasKey("DocumentId", "PartNumber");

                    b.ToTable("DocumentParts");
                });

            modelBuilder.Entity("Aixaminator.Data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DocumentPartNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HighlightColour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "DocumentPartNumber");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Aixaminator.Data.DocumentPart", b =>
                {
                    b.HasOne("Aixaminator.Data.Document", null)
                        .WithMany("Parts")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aixaminator.Data.Note", b =>
                {
                    b.HasOne("Aixaminator.Data.Document", null)
                        .WithMany("Notes")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aixaminator.Data.DocumentPart", null)
                        .WithMany()
                        .HasForeignKey("DocumentId", "DocumentPartNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Aixaminator.Data.HighlightLocation", "Location", b1 =>
                        {
                            b1.Property<int>("NoteId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("EndKey")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("EndOffset")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("StartKey")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("StartOffset")
                                .HasColumnType("INTEGER");

                            b1.HasKey("NoteId");

                            b1.ToTable("Notes");

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Aixaminator.Data.Document", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
