// <auto-generated />
using System;
using Aixaminator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aixaminator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250217123224_UpdateNotesToHandleQuestions")]
    partial class UpdateNotesToHandleQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Aixaminator.Data.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PartsRead")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Aixaminator.Data.DocumentPart", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseColour")
                        .HasColumnType("INTEGER");

                    b.HasKey("DocumentId", "PartNumber");

                    b.ToTable("DocumentParts");
                });

            modelBuilder.Entity("Aixaminator.Data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DocumentPartNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HighlightColour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "DocumentPartNumber");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Aixaminator.Data.DocumentPart", b =>
                {
                    b.HasOne("Aixaminator.Data.Document", null)
                        .WithMany("Parts")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aixaminator.Data.Note", b =>
                {
                    b.HasOne("Aixaminator.Data.Document", "Document")
                        .WithMany("Notes")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aixaminator.Data.DocumentPart", "Part")
                        .WithMany("Notes")
                        .HasForeignKey("DocumentId", "DocumentPartNumber");

                    b.Navigation("Document");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Aixaminator.Data.Document", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Aixaminator.Data.DocumentPart", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
